set(pipeline "builtin.module(ckl-nvidia-materialize-mma-sync,ckl-nvidia-lower-mma-sync,ckl-nvidia-lower-fragment-io,convert-nvgpu-to-nvvm,convert-nvvm-to-llvm,convert-func-to-llvm,expand-strided-metadata,lower-affine,convert-arith-to-llvm,convert-index-to-llvm,canonicalize,cse,gpu.module(convert-gpu-to-nvvm,canonicalize,cse,reconcile-unrealized-casts))")
execute_process(
  COMMAND "${CKL_OPT}" "${INPUT_FILE}" "--pass-pipeline=${pipeline}"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "CKL-to-NVVM pipeline failed:\n${error}")
endif()
if(NOT output MATCHES "nvvm.mma.sync" OR NOT output MATCHES "llvm.func")
  message(FATAL_ERROR "missing NVVM MMA instruction or LLVM kernel:\n${output}")
endif()
if(output MATCHES "ckl\\." OR output MATCHES "ckl_nvidia\\." OR
   output MATCHES "nvgpu\\." OR output MATCHES "gpu.thread_id")
  message(FATAL_ERROR "target-independent or intermediate operations remain:\n${output}")
endif()
string(REGEX MATCHALL "llvm.load" loads "${output}")
list(LENGTH loads load_count)
if(NOT load_count EQUAL 16)
  message(FATAL_ERROR "expected 16 LLVM fragment loads, got ${load_count}:\n${output}")
endif()
string(REGEX MATCHALL "llvm.store" stores "${output}")
list(LENGTH stores store_count)
if(NOT store_count EQUAL 4)
  message(FATAL_ERROR "expected four LLVM result stores, got ${store_count}:\n${output}")
endif()
