execute_process(
  COMMAND "${CKL_OPT}" "${INPUT_FILE}" --ckl-select-alternatives
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "ckl-opt failed:\n${error}")
endif()
string(REGEX MATCHALL "ckl.compose" compositions "${output}")
list(LENGTH compositions composition_count)
if(NOT composition_count EQUAL 2)
  message(FATAL_ERROR "expected two inferred compositions, got ${composition_count}:\n${output}")
endif()
if(NOT output MATCHES "ckl.invoke @producer.*alternative = \"direct\"")
  message(FATAL_ERROR "producer did not select direct alternative:\n${output}")
endif()
if(NOT output MATCHES "ckl.implementation_id = \"producer.direct.v1\"")
  message(FATAL_ERROR "selected implementation identity is missing:\n${output}")
endif()
if(NOT output MATCHES "ckl.graph_score = 150")
  message(FATAL_ERROR "expected graph score 150:\n${output}")
endif()
if(output MATCHES "ckl.task_compose")
  message(FATAL_ERROR "direct invoke graph unexpectedly requires task_compose:\n${output}")
endif()
